### ISSUE TITLE
Inline delimiters don't seem to work

### ISSUE THREAD

**Issue by Kurren123** [zmx0142857/vscode-markdown-asciimath#3]
OS: Windows

I have the following `settings.json` file in my workspace: 

```json
{
    "markdown-asciimath.inlineDelimLeft": "ii",
    "markdown-asciimath.inlineDelimRight": "ii"
}
```

But it's still taking the inline delimiter to be double backticks: 

![image](https://github.com/zmx0142857/vscode-markdown-asciimath/assets/3525980/5a4b7d51-544e-4a08-b3dc-5aaa2a96f885)

**Comment by zmx0142857** [comment]
Sorry, but due to implementations of [markdown-it-asciimath](https://github.com/widcardw/markdown-it-asciimath), the `inlineDelimLeft` has to start with backtick, and `inlineDelimRight` has to end with backtick. For example:
```json
{
    "markdown-asciimath.inlineDelimLeft": "`$",
    "markdown-asciimath.inlineDelimRight": "$`"
}
```
To let user choose delimeters more freely, you may want to contribute to [markdown-it-asciimath](https://github.com/widcardw/markdown-it-asciimath), by the way.
